### ISSUE TITLE
pyinstaller works but file broken (3)

### ISSUE THREAD

**Issue by PresentJay** [PresentJay/FHIR-RESTful-API-CLI#3]
Traceback (most recent call last):
  File "main.py", line 38, in <module>
  File "main.py", line 17, in main
  File "lib_module\cli_decorator.py", line 21, in main_logo
  File "lib_module\cli_decorator.py", line 84, in log
  File "site-packages\pyfiglet\__init__.py", line 65, in figlet_format
  File "site-packages\pyfiglet\__init__.py", line 794, in __init__
  File "site-packages\pyfiglet\__init__.py", line 801, in setFont
  File "site-packages\pyfiglet\__init__.py", line 126, in __init__
  File "site-packages\pyfiglet\__init__.py", line 136, in preloadFont
  File "site-packages\pkg_resources\__init__.py", line 1134, in resource_exists
  File "site-packages\pkg_resources\__init__.py", line 1404, in has_resource
  File "site-packages\pkg_resources\__init__.py", line 1473, in _has
NotImplementedError: Can't perform this operation for unregistered loader type
[23836] Failed to execute script main

**Comment by PresentJay** [comment]
- [reference] https://github.com/pyinstaller/pyinstaller/issues/2389
